### PR TITLE
added new def's security_ticks and watchlists

### PR DESCRIPTION
**Pull request by GoldenEye22**
This patch has two useful def's (maybe) added to positions data. First def that returns the ticker symbol of a given instrument. Second def that returns the watchlists located in the Robinhood application.

### CODE REVIEW

**Comment by aamazie** [comment]
On second thought, since this is just my repo, I'm not going to merge any pull requests. You can submit this to the parent branch if you want. I appreciate the collaboration, though.

**Comment by GoldenEye22** [comment]
Understandable, just giving your code some love since your repository is the only one working right now lol

**Comment by aamazie** [comment]
I apologize. I got nervous that all my code might have been replaced and I know your code has some differences for Python 2. I approved the changes. Never had to approve a PR before.

**Comment by GoldenEye22** [comment]
I forked from your code and just added the two defs. I stopped being an old man last week and converted to pyhton3, so I don't need those fixes anymore.

**Comment by aamazie** [comment]
That explains a lot... except for the fact that my repo doesn't have your additions after merging.... I'm confused. Maybe because I closed it.

And I was right about needing to fix those differences before a merge, so I appreciate you knowing that and covering before you made the PR.

I just made a new commit where I made sure the prices in the order functions are floats, so I'm going to copy and paste your new functions in so that you can just redownload/refork my repo and have everything up to date.

**Comment by aamazie** [comment]
Ok, updated it.

**Comment by GoldenEye22** [comment]
Thanks, I'm all updated! Yea I got sick of manually adding those defs to my Robinhhod.py, so I forked so I could use git properly. I did the PR for some github practice, my functions aren't anything special. Using Python2 wasn't very rational anymore either.

**Pull request closed without merging**
